name: "Update README.md in the latest post's repo"
on:
  push:
    branches:
      - main
      - master
    paths:
      - "_posts/**"

  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Fetch latest post from the _posts directory
        run: |
          LATEST_POST==$(git log -1 --name-only --pretty="" -- _posts/*.md | head -n 1)

          BASENAME=$(basename "$LATEST_POST")
          REPO_NAME=$(echo "$BASENAME" | cut -d'-' -f4- | sed 's/.md$//')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

          TITLE=$(awk -F': ' '/^title:/ {print $2}' "$LATEST_POST" | sed 's/^"//;s/"$//')
          DESCRIPTION=$(awk -F': ' '/^description:/ {print $2}' "$LATEST_POST" | sed 's/^"//;s/"$//')
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

          awk 'BEGIN {found=0} /^---/ {found++; next} found==2 {print}' "$LATEST_POST" > body.md
          {
            echo "# $TITLE"
            echo ""
            echo "$DESCRIPTION"
            echo ""
            cat body.md
          } > ../cleaned-post.md

      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: puth2314/${{ env.REPO_NAME }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: target-repo

      - name: Update README.md in that repository
        run: |
          cat ../cleaned-post.md > target-repo/README.md

      - name: Commit and push updated README.md
        working-directory: target-repo
        run: |
          git config --global user.name "Puthearath Aim"
          git config --global user.email "puthearathaim@protonmail.com"
          git add README.md
          git commit -m "Updated README with latest post"
          git push

      - name: Update GitHub repo description using API
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/puth2314/${{ env.REPO_NAME }} \
            -d "{\"description\":\"${{ env.DESCRIPTION }}\"}"
